project:
  type: website
  output-dir: docs
website:
  title: "Occupancy Models with R-INLA"
  navbar:
    left:
      - href: index.qmd
        text: Fitting Occupancy models with INLA
      - projects.qmd
      - href: space_time_model.qmd
        text: Case study 1
      - href: SCV_model.qmd
        text: Case study 2
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
format:
  html:
    theme: lux
    toc: true
  pdf: default
editor: source

